# Generated by Django 5.2.6 on 2025-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Football Shoes'), ('ball', 'Football'), ('equipment', 'Training Equipment'), ('accessory', 'Accessories'), ('merch', 'Merchandise')], max_length=50),
        ),
    ]
